SELECT B.BOARD_ID, B.WRITER_ID, B.TITLE, B.PRICE,
            CASE
                WHEN B.STATUS = 'SALE' THEN '판매중'
                WHEN B.STATUS = 'RESERVED' THEN '예약중'
                WHEN B.STATUS = 'DONE' THEN '거래완료'
            END STATUS
FROM USED_GOODS_BOARD B
WHERE B.CREATED_DATE BETWEEN '2022-10-05 00:00:00' AND '2022-10-05 23:59:59'
ORDER BY B.BOARD_ID DESC