SELECT USER_ID, NICKNAME, CONCAT_WS(" ", CITY, STREET_ADDRESS1, STREET_ADDRESS2) AS '전체주소', INSERT(INSERT(TLNO, 4, 0, '-'), 9, 0, '-') AS '전화번호'
FROM USED_GOODS_USER
JOIN USED_GOODS_BOARD ON WRITER_ID = USER_ID
GROUP BY WRITER_ID
HAVING COUNT(WRITER_ID) >= 3
ORDER BY USER_ID DESC;
