SELECT B.TITLE, B.BOARD_ID, P.REPLY_ID, P.WRITER_ID, P.CONTENTS, DATE_FORMAT(P.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD B JOIN USED_GOODS_REPLY P
ON B.BOARD_ID = P.BOARD_ID
WHERE B.CREATED_DATE BETWEEN '2022-10-01 00:00:00' AND '2022-10-31 23:59:59'
ORDER BY P.CREATED_DATE ASC, B.TITLE ASC;